import { Application, ApplicationStatus } from "../entity/Application";
import { User, UserType } from "../entity/User";
import { Venue } from "../entity/Venue";
import bcrypt from "bcrypt";

const saltPassword = 10;

export type AdminSeedVenue = Partial<Venue> & {
  vendorUsername: string;
};

export type AdminSeedApplication = Partial<Application> & {
  hirerUsername: string;
  venueName: string;
};

export const ADMIN_USERS: Partial<User>[] = [
  {
    id: 6,
    first_name: "Admin",
    last_name: "User",
    username: "admin",
    password: bcrypt.hashSync("admin", saltPassword),
    email: "admin@gmail.com",
    phone: "",
    role: UserType.ADMIN,
  },
  {
    id: 7,
    first_name: "Grandhall",
    last_name: "Vendor",
    username: "grandhall_vendor",
    email: "grandhall.vendor@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.VENDOR,
    phone: "0412345678",
  },
  {
    id: 8,
    first_name: "Skyline",
    last_name: "Events",
    username: "skyline_events",
    email: "skyline.events@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.VENDOR,
    phone: "0423456789",
  },
  {
    id: 9,
    first_name: "Garden",
    last_name: "Owner",
    username: "gardenvenue_owner",
    email: "gardenvenue.owner@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.VENDOR,
    phone: "0434567890",
  },
  {
    id: 10,
    first_name: "Beachside",
    last_name: "Vendor",
    username: "beachside_vendor",
    email: "beachside.vendor@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.VENDOR,
    phone: "0445678901",
  },
  {
    id: 11,
    first_name: "Royal",
    last_name: "Vendor",
    username: "royalbanquet_vendor",
    email: "royalbanquet.vendor@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.VENDOR,
    phone: "0456789012",
  },
  {
    id: 12,
    first_name: "John",
    last_name: "Hirer",
    username: "john_hirer",
    email: "john.hirer@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.HIRER,
    phone: "0461111111",
  },
  {
    id: 13,
    first_name: "Emma",
    last_name: "Events",
    username: "emma_events",
    email: "emma.events@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.HIRER,
    phone: "0462222222",
  },
  {
    id: 14,
    first_name: "Michael",
    last_name: "Booking",
    username: "michael_booking",
    email: "michael.booking@example.com",
    password: bcrypt.hashSync("password@123", saltPassword),
    role: UserType.HIRER,
    phone: "0463333333",
  },
  {
    id: 15,
    first_name: "Sarah",
    last_name: "Party",
    username: "sarah_party",
    email: "sarah.party@example.com",
    password: bcrypt.hashSync("password@123", saltPassword),
    role: UserType.HIRER,
    phone: "0464444444",
  },
  {
    id: 16,
    first_name: "David",
    last_name: "Corporate",
    username: "david_corporate",
    email: "david.corporate@example.com",
    password: bcrypt.hashSync("password123", saltPassword),
    role: UserType.HIRER,
    phone: "0465555555",
  },
];

export const ADMIN_VENUES: AdminSeedVenue[] = [
  {
    name: "Riverside Hall",
    location: "Southbank",
    capacity: 180,
    price: 1600,
    image: "",
    description: "Modern venue near the river for corporate and social events.",
    is_featured: false,
    rating: null,
    num_ratings: 0,
    suitabilities: ["dinner", "birthday"],
    vendorUsername: "skyline_events",
  },
  {
    name: "Garden Pavilion",
    location: "Carlton",
    capacity: 120,
    price: 1200,
    image: "",
    description: "Outdoor-style venue suitable for parties and small ceremonies.",
    is_featured: true,
    rating: null,
    num_ratings: 0,
    suitabilities: ["birthday", "wedding"],
    vendorUsername: "gardenvenue_owner",
  },
  {
    name: "Skyline Function Room",
    location: "Docklands",
    capacity: 90,
    price: 950,
    image: "",
    description: "Compact function room with city views for private events.",
    is_featured: false,
    rating: null,
    num_ratings: 0,
    suitabilities: ["classical music", "dinner"],
    vendorUsername: "beachside_vendor",
  },
  {
    name: "Classic Banquet Hall",
    location: "Richmond",
    capacity: 220,
    price: 1900,
    image: "",
    description: "Traditional banquet hall for formal dinners and receptions.",
    is_featured: false,
    rating: null,
    num_ratings: 0,
    suitabilities: ["wedding", "dinner"],
    vendorUsername: "royalbanquet_vendor",
  },
];

type ApplicationSeedTuple = [
  eventName: string,
  expectedGuests: number,
  vendorReason: string,
  status: ApplicationStatus,
  hirerUsername: string,
  venueName: string,
  date: string,
  time: string,
  duration: number,
];

const applicationSeeds: ApplicationSeedTuple[] = [
  ["Wedding Reception", 250, "Venue is available for this time.", "accepted", "john_hirer", "Grand Ballroom", "2026-06-10", "18:00:00", 3],
  ["Birthday Celebration", 90, "Suitable for evening event.", "accepted", "emma_events", "Grand Ballroom", "2026-06-17", "18:00:00", 3],
  ["Engagement Party", 120, "", "pending", "michael_booking", "Grand Ballroom", "2026-06-24", "18:00:00", 3],
  ["Corporate Seminar", 150, "Approved for corporate event.", "accepted", "sarah_party", "Grand Ballroom", "2026-06-12", "14:00:00", 2],
  ["University Networking Night", 180, "Capacity is suitable.", "accepted", "david_corporate", "Grand Ballroom", "2026-06-19", "14:00:00", 2],
  ["Business Meetup", 130, "Rejected due to setup clash.", "rejected", "john_hirer", "Grand Ballroom", "2026-06-26", "14:00:00", 2],
  ["Business Awards Night", 160, "Approved.", "accepted", "john_hirer", "Riverside Hall", "2026-06-15", "19:00:00", 4],
  ["Product Launch", 170, "Approved for launch event.", "accepted", "emma_events", "Riverside Hall", "2026-06-22", "19:00:00", 4],
  ["Charity Dinner", 175, "", "pending", "michael_booking", "Riverside Hall", "2026-06-29", "19:00:00", 4],
  ["Saturday Gala", 180, "Approved.", "accepted", "sarah_party", "Riverside Hall", "2026-06-13", "18:00:00", 5],
  ["Community Dinner", 190, "Rejected due to capacity concern.", "rejected", "david_corporate", "Riverside Hall", "2026-06-20", "18:00:00", 5],
  ["Garden Party", 80, "Approved for morning booking.", "accepted", "john_hirer", "Garden Pavilion", "2026-06-18", "10:00:00", 2],
  ["Small Wedding Ceremony", 100, "Approved.", "accepted", "emma_events", "Garden Pavilion", "2026-06-25", "10:00:00", 2],
  ["Family Gathering", 70, "", "pending", "michael_booking", "Garden Pavilion", "2026-07-02", "10:00:00", 2],
  ["Sunday Lunch Event", 110, "Approved.", "accepted", "sarah_party", "Garden Pavilion", "2026-06-14", "12:00:00", 3],
  ["Outdoor Ceremony", 115, "Rejected due to maintenance.", "rejected", "david_corporate", "Garden Pavilion", "2026-06-21", "12:00:00", 3],
  ["Private Meeting", 40, "Approved.", "accepted", "john_hirer", "Skyline Function Room", "2026-06-20", "16:00:00", 3],
  ["Startup Pitch Night", 85, "Approved.", "accepted", "emma_events", "Skyline Function Room", "2026-06-27", "16:00:00", 3],
  ["Training Workshop", 60, "", "pending", "michael_booking", "Skyline Function Room", "2026-07-04", "16:00:00", 3],
  ["Morning Briefing", 50, "Approved.", "accepted", "sarah_party", "Skyline Function Room", "2026-06-11", "09:00:00", 2],
  ["Team Planning Session", 55, "Rejected due to double booking.", "rejected", "david_corporate", "Skyline Function Room", "2026-06-18", "09:00:00", 2],
  ["Formal Dinner", 200, "Approved.", "accepted", "john_hirer", "Classic Banquet Hall", "2026-06-16", "20:00:00", 4],
  ["Cultural Night", 210, "Approved.", "accepted", "emma_events", "Classic Banquet Hall", "2026-06-23", "20:00:00", 4],
  ["Graduation Dinner", 220, "", "pending", "michael_booking", "Classic Banquet Hall", "2026-06-30", "20:00:00", 4],
  ["Saturday Reception", 190, "Approved.", "accepted", "sarah_party", "Classic Banquet Hall", "2026-06-13", "19:00:00", 4],
  ["Anniversary Dinner", 180, "Rejected due to event clash.", "rejected", "david_corporate", "Classic Banquet Hall", "2026-06-20", "19:00:00", 4],
];

export const ADMIN_APPLICATIONS: AdminSeedApplication[] = applicationSeeds.map(
  ([
    eventName,
    expectedGuests,
    vendorReason,
    status,
    hirerUsername,
    venueName,
    date,
    time,
    duration,
  ]) => ({
    eventName,
    expectedGuests,
    vendorReason,
    status,
    hirerUsername,
    venueName,
    date,
    time,
    duration,
  }),
);
