


export const DEFAULT_HISTORY = [
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Trivia Night", dateOfHire: "2025-01-03", venueId: 1, vendorId: 3, rating: 4.5, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Corporate Event", dateOfHire: "2025-01-06", venueId: 2, vendorId: 3, rating: 4.8, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Workshop Session", dateOfHire: "2025-01-09", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Comedy Evening", dateOfHire: "2025-01-12", venueId: 1, vendorId: 3, rating: 4.2, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Networking Night", dateOfHire: "2025-01-15", venueId: 2, vendorId: 3, rating: 4.7, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Live Music Night", dateOfHire: "2025-01-18", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Birthday Party", dateOfHire: "2025-01-21", venueId: 1, vendorId: 3, rating: 4.9, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Charity Dinner", dateOfHire: "2025-01-24", venueId: 2, vendorId: 3, rating: 4.4, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Trivia Night", dateOfHire: "2025-01-27", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Wedding Reception", dateOfHire: "2025-01-30", venueId: 1, vendorId: 3, rating: 5.0, status: "accepted" },

  { hirerId: 1, venueName: "Garden Terrace", location: "Fitzroy", eventName: "Club Meetup", dateOfHire: "2025-02-02", venueId: 4, vendorId: 4, rating: 4.1, status: "accepted" },
  { hirerId: 1, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Networking Night", dateOfHire: "2025-02-05", venueId: 5, vendorId: 4, rating: 4.6, status: "accepted" },
  { hirerId: 1, venueName: "Industrial Loft", location: "Richmond", eventName: "Workshop Session", dateOfHire: "2025-02-08", venueId: 6, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Beachside Hall", location: "St Kilda", eventName: "Birthday Party", dateOfHire: "2025-02-11", venueId: 7, vendorId: 4, rating: 4.3, status: "accepted" },
  { hirerId: 1, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Trivia Night", dateOfHire: "2025-02-14", venueId: 5, vendorId: 4, rating: 4.8, status: "accepted" },
  { hirerId: 1, venueName: "Garden Terrace", location: "Fitzroy", eventName: "Charity Dinner", dateOfHire: "2025-02-17", venueId: 4, vendorId: 4, rating: 4.0, status: "accepted" },
  { hirerId: 1, venueName: "Industrial Loft", location: "Richmond", eventName: "Live Music Night", dateOfHire: "2025-02-20", venueId: 6, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Beachside Hall", location: "St Kilda", eventName: "Corporate Event", dateOfHire: "2025-02-23", venueId: 7, vendorId: 4, rating: 4.2, status: "accepted" },
  { hirerId: 1, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Comedy Evening", dateOfHire: "2025-02-26", venueId: 5, vendorId: 4, rating: 4.7, status: "accepted" },
  { hirerId: 1, venueName: "Garden Terrace", location: "Fitzroy", eventName: "Engagement Party", dateOfHire: "2025-03-01", venueId: 4, vendorId: 4, rating: 4.4, status: "accepted" },

  { hirerId: 1, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Workshop Session", dateOfHire: "2025-03-04", venueId: 8, vendorId: 5, rating: 4.5, status: "accepted" },
  { hirerId: 1, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Wedding Reception", dateOfHire: "2025-03-07", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Club Meetup", dateOfHire: "2025-03-10", venueId: 10, vendorId: 5, rating: 4.1, status: "accepted" },
  { hirerId: 1, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Trivia Night", dateOfHire: "2025-03-13", venueId: 8, vendorId: 5, rating: 4.6, status: "accepted" },
  { hirerId: 1, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Corporate Event", dateOfHire: "2025-03-16", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Networking Night", dateOfHire: "2025-03-19", venueId: 10, vendorId: 5, rating: 4.0, status: "accepted" },
  { hirerId: 1, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Comedy Evening", dateOfHire: "2025-03-22", venueId: 8, vendorId: 5, rating: 4.8, status: "accepted" },
  { hirerId: 1, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Live Music Night", dateOfHire: "2025-03-25", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Workshop Session", dateOfHire: "2025-03-28", venueId: 10, vendorId: 5, rating: 4.3, status: "accepted" },
  { hirerId: 1, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Charity Dinner", dateOfHire: "2025-03-31", venueId: 8, vendorId: 5, rating: 4.7, status: "accepted" },

  { hirerId: 2, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Birthday Party", dateOfHire: "2025-04-03", venueId: 1, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Trivia Night", dateOfHire: "2025-04-06", venueId: 2, vendorId: 3, rating: 4.2, status: "accepted" },
  { hirerId: 2, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Workshop Session", dateOfHire: "2025-04-09", venueId: 3, vendorId: 3, rating: 4.0, status: "accepted" },
  { hirerId: 2, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Comedy Evening", dateOfHire: "2025-04-12", venueId: 1, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Networking Night", dateOfHire: "2025-04-15", venueId: 2, vendorId: 3, rating: 4.4, status: "accepted" },
  { hirerId: 2, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Corporate Event", dateOfHire: "2025-04-18", venueId: 3, vendorId: 3, rating: 4.1, status: "accepted" },
  { hirerId: 2, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Club Meetup", dateOfHire: "2025-04-21", venueId: 1, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Charity Dinner", dateOfHire: "2025-04-24", venueId: 2, vendorId: 3, rating: 4.5, status: "accepted" },
  { hirerId: 2, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Live Music Night", dateOfHire: "2025-04-27", venueId: 3, vendorId: 3, rating: 4.3, status: "accepted" },
  { hirerId: 2, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Wedding Reception", dateOfHire: "2025-04-30", venueId: 1, vendorId: 3, rating: null, status: "rejected" },

  { hirerId: 2, venueName: "Garden Terrace", location: "Fitzroy", eventName: "Trivia Night", dateOfHire: "2025-05-03", venueId: 4, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Birthday Party", dateOfHire: "2025-05-06", venueId: 5, vendorId: 4, rating: 4.6, status: "accepted" },
  { hirerId: 2, venueName: "Industrial Loft", location: "Richmond", eventName: "Corporate Event", dateOfHire: "2025-05-09", venueId: 6, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Beachside Hall", location: "St Kilda", eventName: "Comedy Evening", dateOfHire: "2025-05-12", venueId: 7, vendorId: 4, rating: 4.7, status: "accepted" },
  { hirerId: 2, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Networking Night", dateOfHire: "2025-05-15", venueId: 5, vendorId: 4, rating: 4.5, status: "accepted" },
  { hirerId: 2, venueName: "Garden Terrace", location: "Fitzroy", eventName: "Club Meetup", dateOfHire: "2025-05-18", venueId: 4, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Industrial Loft", location: "Richmond", eventName: "Workshop Session", dateOfHire: "2025-05-21", venueId: 6, vendorId: 4, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Beachside Hall", location: "St Kilda", eventName: "Trivia Night", dateOfHire: "2025-05-24", venueId: 7, vendorId: 4, rating: 4.4, status: "accepted" },
  { hirerId: 2, venueName: "Skyline Rooftop", location: "Carlton", eventName: "Charity Dinner", dateOfHire: "2025-05-27", venueId: 5, vendorId: 4, rating: 4.8, status: "accepted" },
  { hirerId: 2, venueName: "Beachside Hall", location: "St Kilda", eventName: "Live Music Night", dateOfHire: "2025-05-30", venueId: 7, vendorId: 4, rating: 4.3, status: "accepted" },

  { hirerId: 2, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Workshop Session", dateOfHire: "2025-06-02", venueId: 8, vendorId: 5, rating: 4.0, status: "accepted" },
  { hirerId: 2, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Wedding Reception", dateOfHire: "2025-06-05", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Networking Night", dateOfHire: "2025-06-08", venueId: 10, vendorId: 5, rating: 4.2, status: "accepted" },
  { hirerId: 2, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Trivia Night", dateOfHire: "2025-06-11", venueId: 8, vendorId: 5, rating: 4.1, status: "accepted" },
  { hirerId: 2, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Corporate Event", dateOfHire: "2025-06-14", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Comedy Evening", dateOfHire: "2025-06-17", venueId: 10, vendorId: 5, rating: 4.4, status: "accepted" },
  { hirerId: 2, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Club Meetup", dateOfHire: "2025-06-20", venueId: 8, vendorId: 5, rating: 4.3, status: "accepted" },
  { hirerId: 2, venueName: "Banquet Hall Deluxe", location: "Footscray", eventName: "Birthday Party", dateOfHire: "2025-06-23", venueId: 9, vendorId: 5, rating: null, status: "rejected" },
  { hirerId: 2, venueName: "Cozy Meeting Room", location: "Hawthorn", eventName: "Workshop Session", dateOfHire: "2025-06-26", venueId: 10, vendorId: 5, rating: 4.1, status: "accepted" },
  { hirerId: 2, venueName: "Art Gallery Space", location: "Brunswick", eventName: "Charity Dinner", dateOfHire: "2025-06-29", venueId: 8, vendorId: 5, rating: 4.5, status: "accepted" },

  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Trivia Night", dateOfHire: "2025-07-02", venueId: 1, vendorId: 3, rating: 4.6, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Networking Night", dateOfHire: "2025-07-05", venueId: 2, vendorId: 3, rating: 4.7, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Workshop Session", dateOfHire: "2025-07-08", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Birthday Party", dateOfHire: "2025-07-11", venueId: 1, vendorId: 3, rating: 4.8, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Comedy Evening", dateOfHire: "2025-07-14", venueId: 2, vendorId: 3, rating: 4.4, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Club Meetup", dateOfHire: "2025-07-17", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Wedding Reception", dateOfHire: "2025-07-20", venueId: 1, vendorId: 3, rating: 4.9, status: "accepted" },
  { hirerId: 1, venueName: "Riverside Pavilion", location: "Southbank", eventName: "Corporate Event", dateOfHire: "2025-07-23", venueId: 2, vendorId: 3, rating: 4.5, status: "accepted" },
  { hirerId: 1, venueName: "Tech Hub Conference Room", location: "Docklands", eventName: "Live Music Night", dateOfHire: "2025-07-26", venueId: 3, vendorId: 3, rating: null, status: "rejected" },
  { hirerId: 1, venueName: "Grand Ballroom", location: "Melbourne CBD", eventName: "Charity Dinner", dateOfHire: "2025-07-29", venueId: 1, vendorId: 3, rating: 4.7, status: "accepted" }
];